#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

"""Generate the license bundle for Rust crates linked into Lance support."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPOSITORY_ROOT / "external" / "lance-duckdb" / "Cargo.toml"
LOCK_FILE = MANIFEST.with_name("Cargo.lock")
OUTPUT = REPOSITORY_ROOT / "LICENSES" / "lance-rust-dependencies.txt"
LICENSE_PREFIXES = ("license", "copying", "notice", "copyright")
FORBIDDEN_LICENSES = (
    "AGPL-1.0",
    "AGPL-3.0",
    "GPL-2.0-only",
    "GPL-3.0-only",
    "SSPL-1.0",
)


def cargo_metadata() -> dict[str, object]:
    command = [
        "cargo",
        "metadata",
        "--locked",
        "--format-version",
        "1",
        "--manifest-path",
        str(MANIFEST),
    ]
    try:
        output = subprocess.check_output(command, cwd=REPOSITORY_ROOT, text=True)
    except FileNotFoundError as exc:
        raise RuntimeError("cargo is required to inspect Lance dependencies") from exc
    return json.loads(output)


def package_license_files(package: dict[str, object]) -> list[Path]:
    manifest_path = Path(str(package["manifest_path"]))
    package_root = manifest_path.parent
    candidates: set[Path] = set()
    declared = package.get("license_file")
    if declared:
        declared_path = Path(str(declared))
        candidates.add(declared_path if declared_path.is_absolute() else package_root / declared_path)
    for child in package_root.iterdir():
        if child.is_file() and child.name.lower().startswith(LICENSE_PREFIXES):
            candidates.add(child)
    return sorted(path for path in candidates if path.is_file())


def normalized_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n").rstrip() + "\n"


def build_bundle(metadata: dict[str, object]) -> str:
    resolve = metadata.get("resolve")
    root_package_id = resolve.get("root") if isinstance(resolve, dict) else None
    if not root_package_id:
        raise RuntimeError("Cargo metadata is missing the root package id")
    packages = [
        package
        for package in metadata["packages"]  # type: ignore[index]
        if package.get("id") != root_package_id
    ]
    packages.sort(key=lambda package: (str(package["name"]).lower(), str(package["version"])))

    text_by_hash: dict[str, str] = {}
    text_users: dict[str, list[str]] = defaultdict(list)
    inventory: list[str] = []
    errors: list[str] = []

    for package in packages:
        name = str(package["name"])
        version = str(package["version"])
        component = f"{name} {version}"
        expression = str(package.get("license") or "").strip()
        files = package_license_files(package)
        if not expression and not package.get("license_file"):
            errors.append(f"{component}: missing Cargo license metadata")
        for forbidden in FORBIDDEN_LICENSES:
            if forbidden in expression:
                errors.append(f"{component}: forbidden license {forbidden} in {expression!r}")

        hashes: list[str] = []
        for path in files:
            content = normalized_text(path)
            digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
            text_by_hash.setdefault(digest, content)
            text_users[digest].append(f"{component} ({path.name})")
            hashes.append(digest)
        digest_list = ",".join(sorted(set(hashes))) if hashes else "metadata-only"
        source = package.get("source")
        if source is None:
            package_root = Path(str(package["manifest_path"])).parent
            try:
                package_root = package_root.relative_to(REPOSITORY_ROOT)
            except ValueError:
                pass
            source = f"path+{package_root}"
        inventory.append(f"{component} | {expression or 'license-file'} | {source} | {digest_list}")

    if errors:
        raise RuntimeError("\n".join(errors))

    lock_digest = hashlib.sha256(LOCK_FILE.read_bytes()).hexdigest()
    lines = [
        "Vane Lance Rust dependency licenses",
        "====================================",
        "",
        "Generated by scripts/sync_lance_cargo_licenses.py.",
        "Do not edit this file manually.",
        f"Cargo.lock SHA-256: {lock_digest}",
        "",
        "Inventory",
        "---------",
        "name version | SPDX/license expression | Cargo source | license text SHA-256",
        *inventory,
        "",
        "Preserved license and notice texts",
        "----------------------------------",
    ]
    for digest in sorted(text_by_hash):
        lines.extend(
            (
                "",
                f"SHA-256: {digest}",
                "Used by: " + "; ".join(sorted(text_users[digest], key=str.lower)),
                "",
                text_by_hash[digest].rstrip(),
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail instead of rewriting an out-of-date bundle")
    args = parser.parse_args()

    try:
        generated = build_bundle(cargo_metadata())
    except (OSError, RuntimeError, subprocess.CalledProcessError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if args.check:
        if existing != generated:
            print(
                f"error: {OUTPUT.relative_to(REPOSITORY_ROOT)} is stale; run scripts/sync_lance_cargo_licenses.py",
                file=sys.stderr,
            )
            return 1
        print(f"verified {OUTPUT.relative_to(REPOSITORY_ROOT)}")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
